//
//  RecipeService.swift
//  Reciplease
//
//  Created by Ernesto Elias Aquino Cifuentes on 12/06/2022.
//

import Foundation

class RecipeService {
// MARK: - Variables
    weak var viewDelegate: SearchDelegate?
    var listIngredients: [String] = ["chicken", "curry", "tomatoes"]
    var listRecipes: [Recipe] = []

    // MARK: -Singleton Test
    static let shared = RecipeService()
    private init() {}


// MARK: - Funtions

    /**
     This function adds the ingredients entered by the user to the list of ingredients.
     
     - parameter ingredients: String with the ingredient. Multiple ingredients can be added at the same time as long as they are separated by a comma.
     */
    public func addIngredients(_ ingredients: String?) {
        guard let ingredients = ingredients else {return}
        let ingredientWithoutSpaces =  trimmingAllSpaces(ingredients)
        if ingredientWithoutSpaces.isEmpty {
            return
        }
        if ingredientWithoutSpaces.contains(",") {
            let tabIngredients = splitIngredients(ingredientWithoutSpaces)
            for ingredient in tabIngredients {
                refreshListIngredientWith("- " + ingredient.capitalized + "\n")
                listIngredients.append(ingredient)
            }
            clearIngredientTextField()
        } else {
            refreshListIngredientWith("- " + ingredientWithoutSpaces.capitalized + "\n")
            listIngredients.append(ingredientWithoutSpaces)
            clearIngredientTextField()
        }
    }

    func getRecipes() {
        guard !listIngredients.isEmpty else {
            warningMessage("Please enter at least one ingredient.")
            return
        }
        let request = createRequest()
        let networkManager = NetworkManager<RecipeResponse>()
        showActivityIndicator(true)
        networkManager.getInformation(request: request) { recipeResponse, error in
            self.showActivityIndicator(false)
            self.goToSearchResultViewController()
            guard  error == nil,
                   let recipeResponse = recipeResponse else {
                return
            }
            self.addRecipes(recipeResponse)
        }
    }

    /**
     This function adds the recipes received in the request response to the listRepices variable.
     
     - parameter recipes: Response returned by the request.
     */
    private func addRecipes(_ recipes: RecipeResponse) {
        guard let hits = recipes.hits else {return}
        for hit in hits {
            guard var newRecipe = hit.recipe else {return}
            newRecipe.portions = Int(newRecipe.yield ?? 0)
            newRecipe.preparationTime = Int(newRecipe.totalTime ?? 0)
            listRecipes.append(newRecipe)
        }
    }

    /**
     This function trims a string using the comma " , " as a reference.
     
     - parameter ingredients: The string to be trimmed
     
     - returns: Returns a string table with the trimmed elements.
     */
    private func splitIngredients(_ ingredients: String) -> [String] {
        let ingredientsWithoutSpaces = trimmingAllSpaces(ingredients)
        return ingredientsWithoutSpaces.split(separator: ",").map{"\($0)"}
    }

    /**
     This function removes whitespace from a string.
     
     - parameter string: String with spaces to be removed.
     
     - returns: String without spaces or line breaks.
     */
    private func trimmingAllSpaces(_ string: String) -> String {
        return string.components(separatedBy: .whitespacesAndNewlines).joined()
    }

    /**
     This function recovers the url generated by the createURL() function, and builds an optional instance of URL Request.
     
     - returns:  Returns an optional instance of URL Request with GET method.
     */
    private func createRequest() -> URLRequest? {
           guard let url = createURL() else {
               return nil
           }
           let request = URLRequest(url: url)
           return request
       }

    /**
     This function constructs a url using the API key.
     
     - returns: Returns an optional url.
     */
    private func createURL() -> URL? {
        let endPoint = "https://api.edamam.com/api/recipes/v2?"
        let type = "public"
        let ingredients = listIngredients.joined(separator: ",")
        let app_id = "f3afe7be"
        let app_key = "cfa430402075604d56fc1e8c94096b51"

        guard let escapedIngredients = ingredients.addingPercentEncoding(withAllowedCharacters: .urlHostAllowed),
              let url = URL(string: "\(endPoint)type=\(type)&q=\(escapedIngredients)&app_id=\(app_id)&app_key=\(app_key)")
        else {
            return nil
        }
        return url
    }

    
    // MARK: - Funciones de test.


}
